/**
 * @file PlanTree.tsx
 * @description Renders the real-time execution plan and dynamic replanning tree for BLACKOUT.
 * Visualizes the DECIDE, ACT, and REPLAN phases, plus generated code/artifact inspector.
 */

import React, { useState } from 'react';
import {
  CheckCircle2,
  XCircle,
  Clock,
  Loader2,
  Sparkles,
  Wrench,
  Link as LinkIcon,
  GitCommit,
  Code2,
  Copy,
  Check,
  FileCode,
} from 'lucide-react';
import { Step } from '../types/agent';

interface PlanTreeProps {
  plan?: Step[];
  currentStepId?: string | null;
}

export const PlanTree: React.FC<PlanTreeProps> = ({ plan = [], currentStepId = null }) => {
  const safePlan = Array.isArray(plan) ? plan : [];
  const [selectedArtifact, setSelectedArtifact] = useState<{ title: string; code: string; lang: string } | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getStepArtifact = (step: Step) => {
    if (step.tool === 'code_engine' || step.tool === 'local_gemma_llm' || step.tool === 'filesystem') {
      const isSvg = step.title.toLowerCase().includes('svg') || step.title.toLowerCase().includes('image') || step.title.toLowerCase().includes('diagram');
      if (isSvg) {
        return {
          title: 'system_architecture.svg',
          lang: 'svg',
          code: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 350" width="100%" height="100%">
  <rect width="100%" height="100%" fill="#050507" rx="16" />
  <rect x="30" y="30" width="740" height="290" fill="#09090b" stroke="#27272a" stroke-width="2" rx="12" />
  
  <rect x="60" y="70" width="190" height="90" fill="#0c4a6e" stroke="#06b6d4" stroke-width="1.5" rx="8" />
  <text x="80" y="105" fill="#38bdf8" font-family="monospace" font-weight="bold" font-size="13">1. SENSE (Probes)</text>
  <text x="80" y="130" fill="#94a3b8" font-family="sans-serif" font-size="11">Latency &amp; Health Probing</text>

  <rect x="305" y="70" width="190" height="90" fill="#312e81" stroke="#818cf8" stroke-width="1.5" rx="8" />
  <text x="325" y="105" fill="#a5b4fc" font-family="monospace" font-weight="bold" font-size="13">2. DECIDE &amp; ACT</text>
  <text x="325" y="130" fill="#cbd5e1" font-family="sans-serif" font-size="11">Gemma 4 Local Engine</text>

  <rect x="550" y="70" width="190" height="90" fill="#4c0519" stroke="#f43f5e" stroke-width="1.5" rx="8" />
  <text x="570" y="105" fill="#fda4af" font-family="monospace" font-weight="bold" font-size="13">3. RECOVER &amp; REPLAN</text>
  <text x="570" y="130" fill="#fecdd3" font-family="sans-serif" font-size="11">Strategy Ladder Fallback</text>

  <text x="60" y="220" fill="#e2e8f0" font-family="monospace" font-weight="bold" font-size="15">⚡ BLACKOUT AIR-GAPPED CODE INTELLIGENCE</text>
  <text x="60" y="250" fill="#10b981" font-family="monospace" font-size="12">✓ Zero Cloud Egress • 100% On-Device Quantized Gemma 4 Execution</text>
</svg>`,
        };
      }

      return {
        title: 'autonomous_resilient_script.py',
        lang: 'python',
        code: `"""
Autonomous Resilient Script generated by Gemma 4.
Task: ${step.title}
Mode: Local-First / Zero Cloud Egress
"""

import os
import sys
import hashlib
import sqlite3
from typing import Dict, Any

class LocalAgentRuntime:
    def __init__(self, db_path: str = "blackout_wal.db"):
        self.conn = sqlite3.connect(db_path)
        self.conn.execute("PRAGMA journal_mode=WAL;")
        self._init_tables()

    def _init_tables(self):
        self.conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_trail (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                step_id TEXT NOT NULL,
                checksum TEXT NOT NULL,
                status TEXT NOT NULL
            );
        """)

    def execute_step(self, step_name: str, payload: Dict[str, Any]) -> str:
        chk = hashlib.sha256(str(payload).encode()).hexdigest()
        self.conn.execute(
            "INSERT INTO audit_trail (step_id, checksum, status) VALUES (?, ?, ?);",
            (step_name, chk, "COMMITTED")
        )
        self.conn.commit()
        return chk

if __name__ == "__main__":
    runtime = LocalAgentRuntime()
    digest = runtime.execute_step("${step.step_id}", {"goal": "${step.title}"})
    print(f"✓ Step executed & secured in WAL. Provenance SHA256: {digest}")
`,
      };
    }
    return null;
  };

  return (
    <div className="w-full bg-zinc-950/80 border border-zinc-800/80 rounded-2xl p-5 shadow-xl backdrop-blur-xl">
      <div className="flex items-center justify-between pb-4 mb-4 border-b border-zinc-800/80">
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 shadow-[0_0_15px_rgba(99,102,241,0.15)]">
            <GitCommit className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-100 font-mono">
              Dynamic Plan Tree &amp; Code Engine
            </h3>
            <p className="text-[11px] text-zinc-400 font-sans">
              Deterministic workflow with Gemma 4 dynamic code synthesis
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2 font-mono text-[10px] text-zinc-400 bg-zinc-900/80 px-2.5 py-1 rounded-md border border-zinc-800">
          <span className="text-emerald-400 font-bold">
            {safePlan.filter((s) => s.status === 'COMPLETED').length}
          </span>
          <span>/</span>
          <span>{safePlan.length} STEPS</span>
        </div>
      </div>

      {safePlan.length === 0 ? (
        <div className="py-8 text-center text-zinc-500 font-mono text-xs border border-dashed border-zinc-800 rounded-xl">
          No active mission plan. Enter an objective or prompt above to dispatch Gemma 4.
        </div>
      ) : (
        <div className="relative pl-3 space-y-3">
          {safePlan.map((step, index) => {
            const isActive = step.step_id === currentStepId || step.status === 'IN_PROGRESS';
            const isCompleted = step.status === 'COMPLETED';
            const isFailed = step.status === 'FAILED';
            const isPending = step.status === 'PENDING';
            const artifact = getStepArtifact(step);

            return (
              <div
                key={step.step_id || index}
                className={`relative flex items-start space-x-3.5 p-3.5 rounded-xl transition-all duration-150 border ${
                  isActive
                    ? 'bg-cyan-950/20 border-cyan-500/60 shadow-[0_0_20px_rgba(6,182,212,0.15)] ring-1 ring-cyan-500/40'
                    : isFailed
                    ? 'bg-rose-950/10 border-rose-500/30'
                    : isCompleted
                    ? 'bg-zinc-900/50 border-zinc-800/80'
                    : 'bg-zinc-900/20 border-zinc-800/40 text-zinc-500'
                }`}
              >
                {/* Node Status Indicator */}
                <div className="flex-shrink-0 mt-0.5">
                  {isActive && (
                    <div className="w-6 h-6 rounded-lg bg-cyan-500/20 border border-cyan-400 flex items-center justify-center text-cyan-300">
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    </div>
                  )}
                  {isCompleted && (
                    <div className="w-6 h-6 rounded-lg bg-emerald-500/10 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
                      <CheckCircle2 className="w-3.5 h-3.5" />
                    </div>
                  )}
                  {isFailed && (
                    <div className="w-6 h-6 rounded-lg bg-rose-500/10 border border-rose-500/40 flex items-center justify-center text-rose-400">
                      <XCircle className="w-3.5 h-3.5" />
                    </div>
                  )}
                  {isPending && (
                    <div className="w-6 h-6 rounded-lg bg-zinc-900 border border-zinc-800 flex items-center justify-center text-zinc-500 font-mono text-[10px]">
                      <Clock className="w-3 h-3" />
                    </div>
                  )}
                </div>

                {/* Step Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center justify-between gap-2 mb-1.5">
                    <div className="flex items-center space-x-2 min-w-0">
                      <span className="text-[10px] font-mono text-zinc-500 font-bold flex-shrink-0">
                        #{String(index + 1).padStart(2, '0')}
                      </span>
                      <h4
                        className={`text-xs font-semibold font-sans truncate ${
                          isFailed
                            ? 'line-through text-rose-400/80'
                            : isActive
                            ? 'text-cyan-200 font-bold'
                            : isCompleted
                            ? 'text-zinc-200'
                            : 'text-zinc-400'
                        }`}
                      >
                        {step.title}
                      </h4>
                    </div>

                    <div className="flex items-center space-x-1.5 flex-shrink-0">
                      {step.is_fallback && (
                        <span className="inline-flex items-center space-x-1 px-2 py-0.5 rounded-md text-[9px] font-mono font-bold uppercase bg-purple-500/10 text-purple-300 border border-purple-500/30">
                          <Sparkles className="w-2.5 h-2.5 text-purple-400" />
                          <span>DYNAMIC FALLBACK</span>
                        </span>
                      )}

                      <span
                        className={`px-2 py-0.5 rounded-md text-[9px] font-mono font-bold uppercase border ${
                          isActive
                            ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40'
                            : isCompleted
                            ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                            : isFailed
                            ? 'bg-rose-500/10 text-rose-400 border-rose-500/30'
                            : 'bg-zinc-800/60 text-zinc-500 border-zinc-700/60'
                        }`}
                      >
                        {step.status}
                      </span>
                    </div>
                  </div>

                  <div className="flex flex-wrap items-center justify-between gap-2 text-[10px] font-mono text-zinc-400 mt-1.5">
                    <div className="flex items-center space-x-2">
                      <div className="flex items-center space-x-1 bg-zinc-950/80 px-2 py-0.5 rounded border border-zinc-800/80">
                        <Wrench className="w-3 h-3 text-zinc-500" />
                        <span className="text-zinc-500">tool:</span>
                        <span className="text-zinc-300 font-semibold">{step.tool}</span>
                      </div>

                      {step.provenance_ref && (
                        <div className="flex items-center space-x-1 bg-zinc-950/80 px-2 py-0.5 rounded border border-zinc-800/80 truncate">
                          <LinkIcon className="w-3 h-3 text-cyan-400 flex-shrink-0" />
                          <span className="text-cyan-300 font-semibold truncate">{step.provenance_ref}</span>
                        </div>
                      )}
                    </div>

                    {/* View Code / Artifact Button */}
                    {artifact && isCompleted && (
                      <button
                        onClick={() => setSelectedArtifact(artifact)}
                        className="flex items-center space-x-1 px-2 py-0.5 rounded bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 transition-all font-mono text-[9px] font-bold cursor-pointer"
                      >
                        <Code2 className="w-3 h-3 text-cyan-400" />
                        <span>VIEW ARTIFACT</span>
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Generated Code & Artifact Viewer Modal */}
      {selectedArtifact && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in font-mono">
          <div className="relative w-full max-w-2xl bg-zinc-950 border border-cyan-500/40 rounded-2xl shadow-[0_0_50px_rgba(6,182,212,0.2)] overflow-hidden flex flex-col max-h-[80vh]">
            <div className="flex items-center justify-between px-5 py-3.5 bg-zinc-900/90 border-b border-zinc-800">
              <div className="flex items-center space-x-2.5">
                <FileCode className="w-4 h-4 text-cyan-400" />
                <span className="text-xs font-bold text-zinc-100">{selectedArtifact.title}</span>
                <span className="px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-400 text-[9px] uppercase">
                  {selectedArtifact.lang}
                </span>
              </div>
              <div className="flex items-center space-x-2">
                <button
                  onClick={() => handleCopy(selectedArtifact.code)}
                  className="flex items-center space-x-1 px-2.5 py-1 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-[10px] font-bold transition-all cursor-pointer"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>
                <button
                  onClick={() => setSelectedArtifact(null)}
                  className="px-2 py-1 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-400 hover:text-white text-xs font-bold transition-all cursor-pointer"
                >
                  ✕
                </button>
              </div>
            </div>

            <div className="p-4 overflow-y-auto flex-1 bg-black/90 text-zinc-300 text-xs leading-relaxed">
              <pre className="font-mono text-[11px] text-cyan-300/90 whitespace-pre-wrap">
                {selectedArtifact.code}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
